apiVersion: apps/v1
kind: Deployment
metadata:
  name: mogul-mvp-be-payment-deployment
  namespace: mogul-stage
  labels:
    app: mogul-mvp-be-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mogul-mvp-be-payment
  template:
    metadata:
      labels:
        app: mogul-mvp-be-payment
    spec:
      volumes:
      - configMap:
          items:
          - key: .env
            path: .env
          name: mogul-mvp-be-payment
        name: dot-env

      containers:
      - name: mogul-mvp-be-payment
        image: 671826480772.dkr.ecr.us-east-1.amazonaws.com/mogul-mvp-be-payment-stage:latest
        ports:
        - containerPort: 5001
          protocol: TCP
        volumeMounts:
        - name: dot-env
          mountPath: /usr/src/app/.env
          name: dot-env
          subPath: .env
