apiVersion: v1
kind: Service
metadata:
  labels:
    app: mogul-mvp-be-payment
  name: mogul-mvp-be-payment-svc
  namespace: mogul-stage 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: mogul-mvp-be-payment
